import type { MenuItem } from "@/types/AllTypes";
import {
  CalendarDays,
  Compass,
  Drama,
  FileText,
  Flag,
  Flame,
  Ghost,
  Heart,
  Laugh,
  Mountain,
  Music2,
  Play,
  Rocket,
  Search,
  Skull,
  Star,
  Tent,
  TrendingUp,
  Tv,
  Users,
  VenetianMask,
  History,
  Languages,
  Sparkles,
  Swords,
} from "lucide-react";

export const exploreItems: MenuItem[] = [
  {
    title: "Explore",
    to: "/category/explore",
    icon: Compass,
  },
  {
    title: "Trending",
    to: "/category/trending",
    icon: TrendingUp,
  },
  {
    title: "Popular",
    to: "/category/popular",
    icon: Flame,
  },
  {
    title: "Top Rated",
    to: "/category/top-rated",
    icon: Star,
  },
  {
    title: "Upcoming",
    to: "/category/upcoming",
    icon: CalendarDays,
  },
  {
    title: "Now Playing",
    to: "/category/now-playing",
    icon: Play,
  },
  {
    title: "Trending Arabic",
    to: "/category/trending-arabic",
    icon: Languages,
  },
];

export const genreItems: MenuItem[] = [
  {
    title: "Action",
    to: "/genre/action",
    icon: Swords,
    movieGenreId: 28,
    tvGenreId: 10759,
  },
  {
    title: "Adventure",
    to: "/genre/adventure",
    icon: Mountain,
    movieGenreId: 12,
    tvGenreId: 10759, 
  },
  {
    title: "Animation",
    to: "/genre/animation",
    icon: Sparkles,
    movieGenreId: 16,
    tvGenreId: 16,
  },
  {
    title: "Comedy",
    to: "/genre/comedy",
    icon: Laugh,
    movieGenreId: 35,
    tvGenreId: 35,
  },
  {
    title: "Crime",
    to: "/genre/crime",
    icon: VenetianMask,
    movieGenreId: 80,
    tvGenreId: 80,
  },
  {
    title: "Documentary",
    to: "/genre/documentary",
    icon: FileText,
    movieGenreId: 99,
    tvGenreId: 99,
  },
  {
    title: "Drama",
    to: "/genre/drama",
    icon: Drama,
    movieGenreId: 18,
    tvGenreId: 18,
  },
  {
    title: "Family",
    to: "/genre/family",
    icon: Users,
    movieGenreId: 10751,
    tvGenreId: 10751,
  },
  {
    title: "Fantasy",
    to: "/genre/fantasy",
    icon: Sparkles,
    movieGenreId: 14,
    tvGenreId: 10765, 
  },
  {
    title: "History",
    to: "/genre/history",
    icon: History,
    movieGenreId: 36,
    tvGenreId: 36,
  },
  {
    title: "Horror",
    to: "/genre/horror",
    icon: Ghost,
    movieGenreId: 27,
    tvGenreId: 27,
  },
  {
    title: "Music",
    to: "/genre/music",
    icon: Music2,
    movieGenreId: 10402,
    tvGenreId: 10764, 
  },
  {
    title: "Mystery",
    to: "/genre/mystery",
    icon: Search,
    movieGenreId: 9648,
    tvGenreId: 9648,
  },
  {
    title: "Romance",
    to: "/genre/romance",
    icon: Heart,
    movieGenreId: 10749,
    tvGenreId: 10749,
  },
  {
    title: "Science Fiction",
    to: "/genre/science-fiction",
    icon: Rocket,
    movieGenreId: 878,
    tvGenreId: 10765, 
  },
  {
    title: "TV Movie",
    to: "/genre/tv-movie",
    icon: Tv,
    movieGenreId: 10770,
    tvGenreId: undefined,
  },
  {
    title: "Thriller",
    to: "/genre/thriller",
    icon: Skull,
    movieGenreId: 53,
    tvGenreId: undefined,
  },
  {
    title: "War",
    to: "/genre/war",
    icon: Flag,
    movieGenreId: 10752,
    tvGenreId: undefined,
  },
  {
    title: "Western",
    to: "/genre/western",
    icon: Tent,
    movieGenreId: 37,
    tvGenreId: undefined,
  },
];